### ISSUE TITLE
More details about how to use

### ISSUE THREAD

**Issue by lethdat** [singnet/image-matching#1]
Can I get more information or manual about GoodPoint with FIRE dataset ? how do you fine-tuned ?
I want to apply GoodPoint with my medical data

**Comment by noskill** [comment]
Hi @lethdat . I pushed file with training code https://github.com/singnet/image-matching/blob/master/fem/train_fundus.py , it is basically the same code as in train_reinforce.py(training on ms coco). The difference is in image augmentation https://github.com/singnet/image-matching/blob/master/fem/fundus.py. Processing steps are random 1408x1408 crop of an image, resize to 256x256 px,  random homography application together with random noise(see NoisyTransformWithResize and FundusTransformWithResize).

Code should hopefully work on any images, but please note that homography-related code expects square images. It is on my to do list, but i can fix it sooner if you need to run the code on non-cropped images. Please let me know if you encounter any issues.

**Comment by lethdat** [comment]
Dear @noskill. I setup our environment for your code (Python 3.6) 
But it is not working:
![image](https://user-images.githubusercontent.com/65285605/104139720-b6428000-53f0-11eb-9b9a-f924aacfd4ad.png)
I don't know where is "continuous" ? Is your code only support Python 2.7 ?

**Comment by lethdat** [comment]
Traceback (most recent call last):
  File "train_fundus.py", line 8, in <module>
    from fem.reinf_utils import threshold_nms, threshold_nms_dense
  File "/mnt/h/CNN-Projects/GoodPoint/image-matching/fem/reinf_utils.py", line 3, in <module>
    from fem import util
  File "/mnt/h/CNN-Projects/GoodPoint/image-matching/fem/util.py", line 84
    hom_coords = H @ [col_m, row_m, 1]
                                ^
SyntaxError: invalid syntax

What is @ mean ?

**Comment by noskill** [comment]
I pushed conda environment file
https://github.com/singnet/image-matching/blob/master/fem/environment.yml.
Concerning your particular error: something must be wrong with the
environment since __init__.py is in python3.8 env, not in python3.6

пн, 11 янв. 2021 г. в 03:39, lethdat <notifications@github.com>:

**Comment by noskill** [comment]
"@" is matrix multiplication operation. It calls __matmul__ method which is
implemented in numpy and pytorch arrays. It is available since python
version 3.5.

пн, 11 янв. 2021 г. в 11:01, lethdat <notifications@github.com>:

**Comment by lethdat** [comment]
thank you for your support.
